kind: pipeline
name: amd

platform:
  os: linux
  arch: amd64

steps:
- name: common
  image: ocaml/opam2:4.07
  commands:
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add overlays .
  - opam install -y dune
  - eval `opam env`
  - git clone git://github.com/avsm/duniverse && cd duniverse && make && sudo make install PREFIX=/usr/bin && cd .. && rm -rf duniverse
  - opam depext -uiy mirage conf-pkg-config
  - git clone -b duniverse-master git://github.com/dune-universe/mirage-skeleton
  - mv /home/opam/.opam .opam
  - echo done
- name: tutorial/noop
  image: ocaml/opam2:4.07
  depends_on:
  - common
  commands:
  - make OVERLAY_REMOTE=`pwd` EXAMPLE=tutorial/noop

- name: stage1-noop
  image: ocaml/opam2:4.07
  depends_on:
  - tutorial/noop

- name: tutorial/noop-functor
  image: ocaml/opam2:4.07
  depends_on:
  - stage1-noop
  commands:
  - make OVERLAY_REMOTE=`pwd` EXAMPLE=tutorial/noop-functor

- name: tutorial/hello
  image: ocaml/opam2:4.07
  depends_on:
  - stage1-noop
  commands:
  - make OVERLAY_REMOTE=`pwd` EXAMPLE=tutorial/hello

- name: tutorial/hello-key
  image: ocaml/opam2:4.07
  depends_on:
  - stage1-noop
  commands:
  - make OVERLAY_REMOTE=`pwd` EXAMPLE=tutorial/hello-key

- name: tutorial/lwt/echo_server
  image: ocaml/opam2:4.07
  depends_on:
  - stage1-noop
  commands:
  - make OVERLAY_REMOTE=`pwd` EXAMPLE=tutorial/lwt/echo_server

- name: tutorial/lwt/heads1
  image: ocaml/opam2:4.07
  depends_on:
  - stage1-noop
  commands:
  - make OVERLAY_REMOTE=`pwd` EXAMPLE=tutorial/lwt/heads1

- name: tutorial/lwt/heads2
  image: ocaml/opam2:4.07
  depends_on:
  - stage1-noop
  commands:
  - make OVERLAY_REMOTE=`pwd` EXAMPLE=tutorial/lwt/heads2

- name: tutorial/lwt/timeout1
  image: ocaml/opam2:4.07
  depends_on:
  - stage1-noop
  commands:
  - make OVERLAY_REMOTE=`pwd` EXAMPLE=tutorial/lwt/timeout1

- name: tutorial/lwt/timeout2
  image: ocaml/opam2:4.07
  depends_on:
  - stage1-noop
  commands:
  - make OVERLAY_REMOTE=`pwd` EXAMPLE=tutorial/lwt/timeout2


- name: stage2-tutorial
  image: ocaml/opam2:4.07
  depends_on:
  - tutorial/noop-functor
  - tutorial/hello
  - tutorial/hello-key
  - tutorial/lwt/echo_server
  - tutorial/lwt/heads1
  - tutorial/lwt/heads2
  - tutorial/lwt/timeout1
  - tutorial/lwt/timeout2

- name: device-usage/clock
  image: ocaml/opam2:4.07
  depends_on:
  - stage2-tutorial
  commands:
  - make EXAMPLE=device-usage/clock

- name: device-usage/conduit_server
  image: ocaml/opam2:4.07
  depends_on:
  - stage2-tutorial
  commands:
  - make EXAMPLE=device-usage/conduit_server

- name: device-usage/console
  image: ocaml/opam2:4.07
  depends_on:
  - stage2-tutorial
  commands:
  - make EXAMPLE=device-usage/console

- name: device-usage/kv_ro
  image: ocaml/opam2:4.07
  depends_on:
  - stage2-tutorial
  commands:
  - make EXAMPLE=device-usage/kv_ro

- name: device-usage/network
  image: ocaml/opam2:4.07
  depends_on:
  - stage2-tutorial
  commands:
  - make EXAMPLE=device-usage/network

- name: device-usage/ping6
  image: ocaml/opam2:4.07
  depends_on:
  - stage2-tutorial
  commands:
  - make EXAMPLE=device-usage/ping6

- name: device-usage/prng
  image: ocaml/opam2:4.07
  depends_on:
  - stage2-tutorial
  commands:
  - make EXAMPLE=device-usage/prng

- name: stage3-device-usage
  image: ocaml/opam2:4.07
  depends_on:
  - device-usage/clock
  - device-usage/conduit_server
  - device-usage/console
  - device-usage/kv_ro
  - device-usage/network
  - device-usage/ping6
  - device-usage/prng

- name: applications/dhcp
  image: ocaml/opam2:4.07
  depends_on:
  - stage3-device-usage
  commands:
  - make EXAMPLE=applications/dhcp

- name: applications/dns
  image: ocaml/opam2:4.07
  depends_on:
  - stage3-device-usage
  commands:
  - make EXAMPLE=applications/dns

- name: applications/static_website_tls
  image: ocaml/opam2:4.07
  depends_on:
  - stage3-device-usage
  commands:
  - make EXAMPLE=applications/static_website_tls

- name: stage4-applications
  image: ocaml/opam2:4.07
  depends_on:
  - applications/dhcp
  - applications/dns
  - applications/static_website_tls

- name: all
  image: ocaml/opam2:4.07
  depends_on:
  - stage4-applications
